### ISSUE TITLE
Is ios ready ?

### ISSUE THREAD

**Issue by EArminjon** [RohitKumarMishra/wifi_configuration#8]
Hi,

```
This plugin works Android. iOS will be released later.
```
Last update is dated of Nov 21, 2019. Is ios ready ?

**Comment by RohitKumarMishra** [comment]
Hii,
Thanks for using plugin.

This works for android and ios, but for iOS latest version after ios 12 the
support for wifi accessibility APIs is been revoked by Apple so it will not
work for ios.
Thanks,

**Comment by EArminjon** [comment]
Oh sad... Thanks for you reply.

**Comment by EArminjon** [comment]
@RohitKumarMishra  Did you have any alternative :3 ?
